{
 "title": "personalar (temp)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "media", "query": "callback,email,message,voice" },
   { "name": "pcrc0", "label": "PCRC0", "query": "CAR,PAY,RET,SOP,VTA" }
  ]
 },
 "panels": [
  {
   "title": "media",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT SUM(\"count\") as \"waiting\", \"time\" FROM \"temp\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"media\" = '$media' AND \"metric\" = 'oWaiting') GROUP BY \"time\" "
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT SUM(\"count\") as \"interacting\", \"time\" FROM \"temp\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"media\" = '$media' AND \"metric\" = 'oInteracting') GROUP BY \"time\" "
    }
   ]
  },
  {
   "title": "all",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT SUM(\"count\") as \"waiting\", \"time\" FROM \"temp\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"metric\" = 'oWaiting' GROUP BY \"time\""
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT SUM(\"count\") as \"interacting\", \"time\" FROM \"temp\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"metric\" = 'oInteracting' GROUP BY \"time\""
    }
   ]
  },
  {
   "title": "media - PCRC0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT SUM(\"count\") as \"waiting\", \"time\" FROM \"temp\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"media\" = '$media' AND regexp_replace(name::STRING, '^([A-Z]+)_([A-Z]+)_([A-Z]+)_([A-Z]+)_([A-Z]+)_([A-Z]+)_([A-Z]+).*', '$3', 'gi') = '$pcrc0' AND \"metric\" = 'oWaiting') GROUP BY \"time\" "
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT SUM(\"count\") as \"interacting\", \"time\" FROM \"temp\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"media\" = '$media' AND regexp_replace(name::STRING, '^([A-Z]+)_([A-Z]+)_([A-Z]+)_([A-Z]+)_([A-Z]+)_([A-Z]+)_([A-Z]+).*', '$3', 'gi') = '$pcrc0' AND \"metric\" = 'oInteracting') GROUP BY \"time\" "
    }
   ]
  },
  {
   "title": "agents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT SUM(\"count\") as \"on queue\", \"time\" FROM \"pqa\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (name LIKE '%\\_QC1\\_' AND \"metric\" = 'oOnQueueUsers') GROUP BY \"time\" "
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT SUM(\"count\") as \"off queue\", \"time\" FROM \"pqa\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (name LIKE '%\\_QC1\\_' AND \"metric\" = 'oOffQueueUsers' AND \"qualifier\" != 'OFFLINE') GROUP BY \"time\" "
    }
   ]
  }
 ]
}